# -*- coding: utf-8 -*-
"""EstatisticaDescritiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nseXvLEzFr98LHD5XYi-pNv347Of097K
"""

import numpy as np
import pandas as pd

"""##Construção de uma distribuição de frequência

"""

dados = [24,23,22,28,35,21,23,33,34,24,21,25,36,26,22,30,32,25,26,33,34,21,31,25,31,26,25,35,33,31]

"""##Ordenação dos números"""

np.sort(dados)

"""##Amplitude Total"""

Ampli = np.max(dados) - np.min(dados); Ampli

"""##Tamanho Amostral"""

n = len(dados); n

"""##Número de classes fórmula de Sturges

"""

NFS = np.ceil( 1 + 3.22*np.log10(n)); NFS

"""##Amplitude das Classes"""

h = np.ceil(Ampli/NFS); h

"""##Limites das Classes"""

bins = [np.min(dados) + i*h.astype('int') for i in range(NFS.astype('int')+1)]; bins

"""##Frequência dos Dados"""

pd.cut(dados, bins=bins, right=False).value_counts()